# Imagen base oficial de PHP con FPM
FROM php:8.2-fpm

# Instalar dependencias del sistema
RUN apt-get update && apt-get install -y \
    git curl zip unzip \
    libpng-dev libjpeg-dev libonig-dev libxml2-dev \
    libzip-dev sqlite3 libsqlite3-dev \
    && docker-php-ext-install pdo pdo_mysql pdo_sqlite mbstring exif pcntl bcmath gd zip

# Instalar Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Establecer el directorio de trabajo
WORKDIR /var/www

# Copiar archivos del proyecto
COPY . .

# Instalar dependencias de Laravel
RUN composer install --no-interaction --prefer-dist --optimize-autoloader

# Dar permisos a la carpeta de storage y cache
RUN chmod -R 777 storage bootstrap/cache

# Copiar archivo .env si no existe
RUN cp .env.example .env || true

# Generar clave de aplicación (puedes hacerlo desde variables también)
RUN php artisan config:clear && php artisan key:generate

# Exponer el puerto que usa Laravel
EXPOSE 10000

# Comando de inici0
CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=10000"]
